DROP TABLE IF EXISTS todo;
DROP TABLE IF EXISTS recipe;
DROP TABLE IF EXISTS grade;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS todos;
DROP TABLE IF EXISTS recipes;
DROP TABLE IF EXISTS grades;
DROP TABLE IF EXISTS users;